### ISSUE TITLE
Setup_assistant can't load the kinematic.yaml file it generated earlier

### ISSUE THREAD

**Issue by facontidavide** [moveit/moveit_setup_assistant#99]
Version: latest git
Platform: Ubuntu 14.04, ROS Indigo

When I try to edit an existing configuration, created using setup_assistant itself, the method MoveItConfigData::inputKinematicsYAML can find the group_name (in this case "manipulator", but none of its fields.

all of the conditions:

```
          if( prop_name = findValue( group_it.second(), "..." ) )
```

return false.

This is the content of the file:

```
        manipulator:
          kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
          kinematics_solver_search_resolution: 0.01
          kinematics_solver_timeout: 0.005
          kinematics_solver_attempts: 3
```
